### ISSUE TITLE
[Easymport] Automatically import projects to a parent project working sets (if one exists)

### ISSUE THREAD

**Issue by ilx** [jbosstools/jbosstools-playground#31] opened 2015-01-07 09:32 UTC
I have noticed that projects are not automatically imported into a "parent project" working set anymore.
Is it viable to make it a preference on a worspace level?
I would like to avoid wizard on "Import project" if possible.

Is this related to #29 ?

**Comment by mickaelistria** [comment] 2015-01-07 10:06
Can you please give detailed steps to reproduce?

**Comment by ilx** [comment] 2015-01-07 11:30
I have gradle based build:
- execute gradle eclipse
- import root project
- associate root project to  a working set
- select newly created working set
- import one of the nested projects - it's not associated to the root project working set - I have to associate it manually

**Comment by mickaelistria** [comment] 2015-01-07 11:32
Which procedure do you use to "import one of the nested projects". There are many ways of doing this now :)

**Comment by ilx** [comment] 2015-01-07 11:34
Right click on a folder in Project explorer and select Import as Project. :)

**Comment by mickaelistria** [comment] 2015-01-08 13:17
This "Import as Project" context menu action is part of Eclipse Platform UI. Cf https://bugs.eclipse.org/bugs/show_bug.cgi?id=427774 .
So you should open this request for inheritance of working sets to the Platform UI bugtracker. Please make add me as CC of the ticket once it's opened.

Closing for jbosstools-playground. If GitHub would allow ticket status, it would probably be CLOSED UPSTREAM.

**Closed by mickaelistria** 2015-01-08 13:17 UTC

**Comment by ilx** [comment] 2015-01-08 16:27
Ah. I didn't spied on it. OTOH, how do I use easymport to achieve this? :)

**Comment by ilx** [comment] 2015-01-08 16:36
I guess I would have to use Import -> Import Projects from Folder... 
The problem is that it doesn't offer me working sets. Is this a bug or I'm using too old version?

**Comment by mickaelistria** [comment] 2015-01-08 16:44
If you select a working set and then use "File > Import Projects from Folder", the selected working set should include the new projects.

**Comment by ilx** [comment] 2015-01-08 17:00
It doesn't work for me. I have a folder structure like: xl-platform/xl-test-utils/scala-base if that matters?

In this scenario I have to select folder on a disk. I already have a top level project open and expected I could right click somewhere and import visible folder as project.

I have already imported xl-platform into xl-platform workingset and I have started import on xl-test-utils (with working set selected like you suggested) and it didn't work. Project was imported but not associated to the working set.

Btw. do I really have to select working set? After I have started using nested projects I have only one working set enabled at the time with Top level elements -> Projects (which is a default).

**Comment by mickaelistria** [comment] 2015-01-08 17:04
>  Project was imported but not associated to the working set.

Well, that seems to be a bug. I'll try to have a look, but I've many things in my todo-list at the moment, so I can't tell when I'll be able to work on it. So if you have some time to investigate that an contribute a patch to Easymport command handler, that would be great.

> Btw. do I really have to select working set? After I have started using nested projects I have only one working set enabled at the time with Top level elements -> Projects (which is a default).

Nested projects are totally independent from working sets, you don't need working sets to have nested projects. Initially the goal of nested project was exactly to get rid of working sets which are more a workaround to organize project explorer.

**Comment by mickaelistria** [comment] 2015-01-08 17:22
I just gave it a try, and I can confirm that as you reported, using Import Folder as Project when a working set is selected does NOT work.

**Comment by maxandersen** [comment] 2015-01-12 12:58
@mickaelistria working sets are relevant *even* when you have nestor IMO.

You can use workingset to group across your physical hiearchy. thus having explicit "add to working set" field would make sense imo.
